spring.application.name=veterinaria

# Nombre de la base de datos que creaste en MongoDB Compass
spring.data.mongodb.database=veterinaria_samurai

# Dirección local del servidor de Mongo
spring.data.mongodb.host=localhost

# Puerto estándar que verificamos que estaba escuchando en tu CMD
spring.data.mongodb.port=27017
